// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btjhljhwoyyuozbhdlek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0amhsamh3b3l5dW96YmhkbGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTk3ODcsImV4cCI6MjA3MzU5NTc4N30.8xKXO9W0IOWWWFxC7Bk714SbFksZvy2BHCjuwF1JRTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});